In [8]:
import pandas as pd
import numpy as np
import re

In [193]:
def logs():
    with open("logdata.txt", "r") as file:
        logdata = file.read()
        df=pd.DataFrame([{
        
            "host":re.findall("\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}",word)[0],
            "user_name":re.findall("- ([a-z0-9]+) | - -",word)[0],
            "date":re.findall("\d{1,2}\S+ -[0-9]+",word)[0][:11],
            "time":re.findall("\d{1,2}\S+ -[0-9]+",word)[0][12:20],
            "Action" :re.findall("POST.+\"|GET.+\"|PATCH.+\"|HEAD.+\"|DELETE.+\"|PUT.+\" ",word)[0][:4],
            "request":re.findall(" /.+\ ",word)[0][2:-1] 
            
        } for word in logdata.splitlines() ])
        
   
        
    return  df

In [194]:
log()

,host,user_name,date,time,Action,request
0,146.204.224.152,feest6811,21/Jun/2019,15:45:24,POST,"incentivize HTTP/1.1"" 302"
1,197.109.77.178,kertzmann3129,21/Jun/2019,15:45:25,DELE,"virtual/solutions/target/web+services HTTP/2.0"" 203"
2,156.127.178.177,okuneva5222,21/Jun/2019,15:45:27,DELE,"interactive/transparent/niches/revolutionize HTTP/1.1"" 416"
3,100.32.205.59,ortiz8891,21/Jun/2019,15:45:28,PATC,"architectures HTTP/1.0"" 204"
4,168.95.156.240,stark2413,21/Jun/2019,15:45:31,GET,"engage HTTP/2.0"" 201"
...,...,...,...,...,...,...
974,135.186.69.192,,21/Jun/2019,16:01:58,PATC,"best-of-breed HTTP/1.1"" 405"
975,32.86.3.51,,21/Jun/2019,16:01:59,GET,"optimize/impactful/sexy/channels HTTP/2.0"" 405"
976,176.68.62.252,turner3261,21/Jun/2019,16:02:00,GET,"viral HTTP/1.1"" 405"
977,35.86.149.61,zemlak6334,21/Jun/2019,16:02:01,HEAD,"incentivize HTTP/2.0"" 304"
978,30.95.91.251,larson8319,21/Jun/2019,16:02:02,PUT,"one-to-one/whiteboard HTTP/1.0"" 401"

In [195]:
log().info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 979 entries, 0 to 978
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   host       979 non-null    object
 1   user_name  979 non-null    object
 2   date       979 non-null    object
 3   time       979 non-null    object
 4   Action     979 non-null    object
 5   request    979 non-null    object
dtypes: object(6)
memory usage: 46.0+ KB